# Resources

We are using the [this](https://github.com/srush/Tensor-Puzzles/tree/main) to solve pytorch problems

In [1]:
import torch
import numpy as np
from torchtyping import TensorType as TT
tensor = torch.tensor
tensor

<function torch._VariableFunctionsClass.tensor>

In [2]:
def arange(i: int):
    "Use this function to replace a for-loop."
    return torch.tensor(range(i))

In [3]:
def where(q, a, b):
    "Use this function to replace an if-statement."
    return (q * a) + (~q) * b

In [4]:
s = torch.tensor(range(5))

t = torch.tensor(range(5))[:, None]

In [5]:
s, t

(tensor([0, 1, 2, 3, 4]),
 tensor([[0],
         [1],
         [2],
         [3],
         [4]]))

In [6]:
list1 = [val for val in range(5)]
list1 = torch.tensor(list1)
list1

tensor([0, 1, 2, 3, 4])

In [7]:
s[0], t[0], list1[0], s.shape, t.shape, list1.shape

(tensor(0),
 tensor([0]),
 tensor(0),
 torch.Size([5]),
 torch.Size([5, 1]),
 torch.Size([5]))

In [8]:
# Broadcast arrays
a = s + t 
a, a.shape

(tensor([[0, 1, 2, 3, 4],
         [1, 2, 3, 4, 5],
         [2, 3, 4, 5, 6],
         [3, 4, 5, 6, 7],
         [4, 5, 6, 7, 8]]),
 torch.Size([5, 5]))

In [9]:
examples = [(tensor([False]), tensor([10]), tensor([0])),
            (tensor([False, True]), tensor([1, 1]), tensor([-10, 0])),
            (tensor([False, True]), tensor([1]), tensor([-10, 0])),
            (tensor([[False, True], [True, False]]), tensor([1]), tensor([-10, 0])),
            (tensor([[False, True], [True, False]]), tensor([[0], [10]]), tensor([-10, 0])),
           ]

In [10]:
for q, a, b in examples:
    p = where(q, a, b)
    print(p, q, a, b, a.shape, b.shape)

tensor([0]) tensor([False]) tensor([10]) tensor([0]) torch.Size([1]) torch.Size([1])
tensor([-10,   1]) tensor([False,  True]) tensor([1, 1]) tensor([-10,   0]) torch.Size([2]) torch.Size([2])
tensor([-10,   1]) tensor([False,  True]) tensor([1]) tensor([-10,   0]) torch.Size([1]) torch.Size([2])
tensor([[-10,   1],
        [  1,   0]]) tensor([[False,  True],
        [ True, False]]) tensor([1]) tensor([-10,   0]) torch.Size([1]) torch.Size([2])
tensor([[-10,   0],
        [ 10,   0]]) tensor([[False,  True],
        [ True, False]]) tensor([[ 0],
        [10]]) tensor([-10,   0]) torch.Size([2, 1]) torch.Size([2])


## Basic functions

Use the above functions to understand pytorch tensor

## Puzzle 1 - ones

In [11]:
# Creating tensor of ones

def ones_spec(out):
    for i in range(len(out)):
        out[i] = 1
        
def ones(i: int) -> TT["i"]:
    out = torch.tensor(np.ones(i), dtype = int)
    return out

t = ones(5)
t

tensor([1, 1, 1, 1, 1])

## Puzzle 2 - sum

In [12]:
def sum_spec(a, out):
    out[0] = 0
    for i in range(len(a)):
        out[0] += a[i]
        
def sum(a: TT["i"]) -> TT[1]:
    print(a)
    out = np.sum([a[i] for i in range(len(a))])
    out = [out]
    return torch.tensor(out)

t = ones(5)
t = sum(t)
t

tensor([1, 1, 1, 1, 1])


tensor([5])

## Puzzle 3 - outer

In [13]:
def outer_spec(a, b, out):
    for i in range(len(out)):
        for j in range(len(out[0])):
            out[i][j] = a[i] * b[j]
            
def outer(a: TT["i"], b: TT["j"]) -> TT["i", "j"]:
    out = np.ones((len(a), len(b)), dtype = float)
    out = np.outer(a, b)
    return torch.tensor(out)

a = torch.tensor([ 2,  2,  2, -1])
b = torch.tensor([[4, 4, 4, 4, 4]])
out = outer(a, b)
out

tensor([[ 8,  8,  8,  8,  8],
        [ 8,  8,  8,  8,  8],
        [ 8,  8,  8,  8,  8],
        [-4, -4, -4, -4, -4]])

## Puzzle 4 - diag

In [14]:
def diag_spec(a, out):
    for i in range(len(a)):
        out[i] = a[i][i]
        
def diag(a: TT["i", "i"]) -> TT["i"]:
    out = np.diag(a, k=0)
    return torch.tensor(out)

a = torch.tensor([[ 3,  3,  3,  3],
        [ 3, -5,  3,  3],
        [ 0,  3,  3,  3],
        [ 3,  3,  3,  3]])
out = diag(a)
print(out)

tensor([ 3, -5,  3,  3])


## Puzzle 5 - eye

In [15]:
def eye_spec(out):
    for i in range(len(out)):
        out[i][i] = 1
        
def eye(j: int) -> TT["j", "j"]:
    out = np.eye(j, dtype = int)
    return torch.tensor(out)

out = eye(5)
print(out)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])


## Puzzle 6 - triu

In [ ]:
def triu_spec(out):
    for i in range(len(out)):
        for j in range(len(out)):
            if i <= j:
                out[i][j] = 1
            else:
                out[i][j] = 0
                
def triu(j: int) -> TT["j", "j"]:
    out = np.zeros((j,j), dtype = int)
    for i in range(j):
      for k in range(j):
        if i <= k:
          out[i,k] = 1
    return torch.tensor(out)
out = triu(5)
print(out)

## Puzzle 7 - cumsum

In [17]:
def cumsum_spec(a, out):
    total = 0
    for i in range(len(out)):
        out[i] = total + a[i]
        total += a[i]

def cumsum(a: TT["i"]) -> TT["i"]:
    out = np.cumsum(a)
    return torch.tensor(out)

a = torch.tensor([ 0, -4,  5])
out = cumsum(a)
print(out)

tensor([ 0, -4,  1])


/tmp/ipykernel_59800/2591688250.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(out)


## Puzzle 8 - diff

In [19]:
def diff_spec(a, out):
    out[0] = a[0]
    for i in range(1, len(out)):
        out[i] = a[i] - a[i - 1]

def diff(a: TT["i"], i: int) -> TT["i"]:
    out = np.zeros(len(a), dtype = int)
    out[0] = a[0]
    for i in range(1, len(out)):
        out[i] = a[i] - a[i - 1]
    return torch.tensor(out)
a = torch.tensor([-2, -2, -2,  0]) 
i = 3
out = diff(a, i)
print(out)

tensor([-2,  0,  0,  2])


## Puzzle 9 - vstack

In [20]:
def vstack_spec(a, b, out):
    for i in range(len(out[0])):
        out[0][i] = a[i]
        out[1][i] = b[i]

def vstack(a: TT["i"], b: TT["i"]) -> TT[2, "i"]:
    out = np.vstack((a,b))
    return torch.tensor(out)

a = torch.tensor([ 3,  0, -3,  4]) 
b = torch.tensor([-2, -5, -1,  0])
out = vstack(a,b)
print(out)

tensor([[ 3,  0, -3,  4],
        [-2, -5, -1,  0]])


## Puzzle 10 - roll

In [21]:
def roll_spec(a, out):
    for i in range(len(out)):
        if i + 1 < len(out):
            out[i] = a[i + 1]
        else:
            out[i] = a[i + 1 - len(out)]
            
def roll(a: TT["i"], i: int) -> TT["i"]:
    return torch.tensor(np.roll(a, shift = i-1))

a = torch.tensor([ 4,  0,  0, -4, -4]) 
b = torch.tensor(5)
out = roll(a, b)
print(out)

tensor([ 0,  0, -4, -4,  4])


## Puzzle 11 - flip

In [23]:
def flip_spec(a, out):
    for i in range(len(out)):
        out[i] = a[len(out) - i - 1]
        
def flip(a: TT["i"], i: int) -> TT["i"]:
    out = np.zeros((len(a)), dtype = int)
    for i in range(len(out)):
        out[i] = a[len(out) - i - 1]
    return torch.tensor(out)

a = torch.tensor([-1, -1, -5, -1]) 
i = torch.tensor(4)
out = flip(a,i)
print(out)

tensor([-1, -5, -1, -1])


## Puzzle 12 - compress

In [24]:
def compress_spec(g, v, out):
    j = 0
    for i in range(len(g)):
        if g[i]:
            out[j] = v[i]
            j += 1
            
def compress(g: TT["i", bool], v: TT["i"], i:int) -> TT["i"]:
    out = np.zeros((len(v)), dtype = int)
    j = 0
    for i in range(len(g)):
        if g[i]:
            out[j] = v[i]
            j += 1
    return torch.tensor(out)

g = torch.tensor([True, True, True]) 
v = torch.tensor([ 1, -2, -3]) 
i = torch.tensor(3)
print(compress(g,v,i))

tensor([ 1, -2, -3])


## Puzzle 13 - pad_to

In [25]:
def pad_to_spec(a, out):
    for i in range(min(len(out), len(a))):
        out[i] = a[i]


def pad_to(a: TT["i"], i: int, j: int) -> TT["j"]:
    out = np.zeros(max(i,j), dtype = int)
    for k in range(min(len(out), len(a))):
        out[k] = a[k]
    out = out[:j]
    return torch.tensor(out)

a = torch.tensor([0, 0, 0, 0, 0]) 
i = torch.tensor(5) 
j = torch.tensor(3)
print(pad_to(a, i, j))

tensor([0, 0, 0])


## Puzzle 14 - sequence_mask

In [26]:
def sequence_mask_spec(values, length, out):
    for i in range(len(out)):
        for j in range(len(out[0])):
            if j < length[i]:
                out[i][j] = values[i][j]
            else:
                out[i][j] = 0
    
def sequence_mask(values: TT["i", "j"], length: TT["i", int]) -> TT["i", "j"]:
    l = length[0]
    arr = np.zeros(len(values[0]), dtype = int)
    for j in range(l):
      arr[j] = 1
    bool_arr = np.array(arr, dtype='bool') 
    out = compress(bool_arr, values[0,:], 0)

    for i in range(1, len(length)):
      l = length[i]
      arr = np.zeros(len(values[0]), dtype = int)
      for j in range(l):
        arr[j] = 1
      bool_arr = np.array(arr, dtype='bool') 
      temp = compress(bool_arr, values[i,:], i)
      out = vstack(out, temp)
    return out


def constraint_set_length(d):
    d["length"] = d["length"] % d["values"].shape[1]
    return d

a = torch.tensor([[ 3,  5, -2],
        [-2,  0,  2],
        [-3,  0,  0],
        [-5, -5,  4]]) 
b = torch.tensor([2, 2, 2, 2])

print(sequence_mask(a,b))


tensor([[ 3,  5,  0],
        [-2,  0,  0],
        [-3,  0,  0],
        [-5, -5,  0]])


## Puzzle 15 - bincount

In [27]:
def bincount_spec(a, out):
    for i in range(len(a)):
        out[a[i]] += 1
    # print(1, a, out)
        
def bincount(a: TT["i"], j: int) -> TT["j"]:

    out = np.bincount(a)
    out = pad_to(out, len(out), j)
    print(a, j)
    return torch.tensor(out)


def constraint_set_max(d):
    d["a"] = d["a"] % d["return"].shape[0]
    return d

a = torch.tensor([2, 2, 2, 2, 2]) 
j = torch.tensor(3)
print(bincount(a, j))

tensor([2, 2, 2, 2, 2]) tensor(3)
tensor([0, 0, 5])


/tmp/ipykernel_59800/2799107016.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(out)


## Puzzle 16 - scatter_add

In [28]:
def scatter_add_spec(values, link, out):
    for j in range(len(values)):
        out[link[j]] += values[j]
        
def scatter_add(values: TT["i"], link: TT["i"], j: int) -> TT["j"]:
    out = np.zeros(max(len(values), j), dtype = int)
    for k in range(len(values)):
        out[link[k]] += values[k]
    out = out[:j]
    return torch.tensor(out)


def constraint_set_max(d):
    d["link"] = d["link"] % d["return"].shape[0]
    return d

values = torch.tensor([-2,  0,  1,  1,  1]) 
link = torch.tensor([1, 1, 2, 1, 2]) 
j = torch.tensor(4)
print(scatter_add(values, link, j))

tensor([ 0, -1,  2,  0])


## Puzzle 17 - flatten

In [31]:
def flatten_spec(a, out):
    k = 0
    for i in range(len(a)):
        for j in range(len(a[0])):
            out[k] = a[i][j]
            k += 1

def flatten(a: TT["i", "j"], i:int, j:int) -> TT["i * j"]:
    out = a[0,:]
    for k in range(1, i):
      out = np.hstack((out, a[k, :]))
    return torch.tensor(out)

a = torch.tensor([[ 0, -3, -5,  0],
        [ 3, -2, -4,  0],
        [ 2,  0,  5, -5]])
i = torch.tensor(3) 
j = torch.tensor(4)
print(flatten(a, i, j))

tensor([ 0, -3, -5,  0,  3, -2, -4,  0,  2,  0,  5, -5])


## Puzzle 18 - linspace

In [32]:
def linspace_spec(i, j, out):
    for k in range(len(out)):
        out[k] = float(i + (j - i) * k / max(1, len(out) - 1))

def linspace(i: TT[1], j: TT[1], n: int) -> TT["n", float]:
    out = np.zeros(n, dtype = np.float32)
    for k in range(len(out)):
        out[k] = float(i + (j - i) * k / max(1, len(out) - 1))
    return torch.tensor(out)

i = torch.tensor([2]) 
j = torch.tensor([-2]) 
n = torch.tensor(5)
print(linspace(i, j, n))

tensor([ 2.,  1.,  0., -1., -2.])


## Puzzle 19 - heaviside

In [33]:
def heaviside_spec(a, b, out):
    for k in range(len(out)):
        if a[k] == 0:
            out[k] = b[k]
        else:
            out[k] = int(a[k] > 0)

def heaviside(a: TT["i"], b: TT["i"]) -> TT["i"]:
    return torch.tensor(np.heaviside(a, b), dtype = int)

a = torch.tensor([1, 1, 1]) 
b = torch.tensor([-3, -1,  1])
print(heaviside(a,b))

tensor([1, 1, 1])


/tmp/ipykernel_59800/2408483715.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(np.heaviside(a, b), dtype = int)


## Puzzle 20 - repeat (1d)

In [34]:
def repeat_spec(a, d, out):
    for i in range(d[0]):
        for k in range(len(a)):
            out[i][k] = a[k]
    print(1, a, d, out)

def constraint_set(d):
    d["d"][0] = d["return"].shape[0]
    return d

            
def repeat(a: TT["i"], d: TT[1]) -> TT["d", "i"]:
    out = a
    for i in range(1, d[0]):
      out = vstack(out, a)
    return out

a = torch.tensor([0, 3, 0, 3, 0])
d = torch.tensor([4])
print(repeat(a, d))

tensor([[0, 3, 0, 3, 0],
        [0, 3, 0, 3, 0],
        [0, 3, 0, 3, 0],
        [0, 3, 0, 3, 0]])


In [35]:
def bucketize_spec(v, boundaries, out):
    for i, val in enumerate(v):
        out[i] = 0
        for j in range(len(boundaries)-1):
            if val >= boundaries[j]:
                out[i] = j + 1
        if val >= boundaries[-1]:
            out[i] = len(boundaries)
    print(v, boundaries, out)


def constraint_set(d):
    d["boundaries"] = np.abs(d["boundaries"]).cumsum()
    return d

            
def bucketize(v: TT["i"], boundaries: TT["j"]) -> TT["i"]:
    out = np.zeros(len(v), dtype = int)
    for i, val in enumerate(v):
        out[i] = 0
        for j in range(len(boundaries)-1):
            if val >= boundaries[j]:
                out[i] = j + 1
        if val >= boundaries[-1]:
            out[i] = len(boundaries)
    return torch.tensor(out)

v = torch.tensor([5, 5, 5, 5]) 
boundaries = torch.tensor([ 5,  5,  7,  9, 12])

print(bucketize(v, boundaries))

tensor([2, 2, 2, 2])
