# Resources

We are using the [this](https://github.com/srush/Tensor-Puzzles/tree/main) to solve pytorch problems

In [1]:
import torch
import numpy as np
from torchtyping import TensorType as TT
tensor = torch.tensor
tensor

<function torch._VariableFunctionsClass.tensor>

In [2]:
def arange(i: int):
    "Use this function to replace a for-loop."
    return torch.tensor(range(i))

In [3]:
def where(q, a, b):
    "Use this function to replace an if-statement."
    return (q * a) + (~q) * b

In [4]:
s = torch.tensor(range(5))

t = torch.tensor(range(5))[:, None]

In [5]:
s, t

(tensor([0, 1, 2, 3, 4]),
 tensor([[0],
         [1],
         [2],
         [3],
         [4]]))

In [6]:
list1 = [val for val in range(5)]
list1 = torch.tensor(list1)
list1

tensor([0, 1, 2, 3, 4])

In [7]:
s[0], t[0], list1[0], s.shape, t.shape, list1.shape

(tensor(0),
 tensor([0]),
 tensor(0),
 torch.Size([5]),
 torch.Size([5, 1]),
 torch.Size([5]))

In [8]:
# Broadcast arrays
a = s + t 
a, a.shape

(tensor([[0, 1, 2, 3, 4],
         [1, 2, 3, 4, 5],
         [2, 3, 4, 5, 6],
         [3, 4, 5, 6, 7],
         [4, 5, 6, 7, 8]]),
 torch.Size([5, 5]))

In [9]:
examples = [(tensor([False]), tensor([10]), tensor([0])),
            (tensor([False, True]), tensor([1, 1]), tensor([-10, 0])),
            (tensor([False, True]), tensor([1]), tensor([-10, 0])),
            (tensor([[False, True], [True, False]]), tensor([1]), tensor([-10, 0])),
            (tensor([[False, True], [True, False]]), tensor([[0], [10]]), tensor([-10, 0])),
           ]

In [10]:
for q, a, b in examples:
    p = where(q, a, b)
    print(p, q, a, b, a.shape, b.shape)

tensor([0]) tensor([False]) tensor([10]) tensor([0]) torch.Size([1]) torch.Size([1])
tensor([-10,   1]) tensor([False,  True]) tensor([1, 1]) tensor([-10,   0]) torch.Size([2]) torch.Size([2])
tensor([-10,   1]) tensor([False,  True]) tensor([1]) tensor([-10,   0]) torch.Size([1]) torch.Size([2])
tensor([[-10,   1],
        [  1,   0]]) tensor([[False,  True],
        [ True, False]]) tensor([1]) tensor([-10,   0]) torch.Size([1]) torch.Size([2])
tensor([[-10,   0],
        [ 10,   0]]) tensor([[False,  True],
        [ True, False]]) tensor([[ 0],
        [10]]) tensor([-10,   0]) torch.Size([2, 1]) torch.Size([2])


## Basic functions

Use the above functions to understand pytorch tensor

In [15]:
# Creating tensor of ones

def ones_spec(out):
    for i in range(len(out)):
        out[i] = 1
        
def ones(i: int) -> TT["i"]:
    out = torch.tensor(np.ones(i), dtype = int)
    return out

t = ones(5)
t

tensor([1, 1, 1, 1, 1])